name: System Tests

on:
  push:
    branches: [main]
    tags: ['v*']
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '39 13 * * *'

jobs:
  system_tests:
    name: System Tests (${{ matrix.os }})
    strategy:
      matrix:
        os: [ ubuntu-22.04, macos-14, ubuntu-22.04-arm ]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 35 # runtime across all OSs, runs can get queued
    steps:
    - name: Runner Info
      run: printenv | sort

    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: '0' # need full history to get version from git tag

    - name: Install packaged dependencies
      run: .github/install_dependencies

    - name: Build
      run: VERBOSE=1 scripts/build_all_combos

    - name: Unit Tests
      run: scripts/run_unit_tests

    - name: Install uv
      uses: astral-sh/setup-uv@v5

    - name: Install Python
      run: uv python install 3.11

    - name: Install test dependencies
      run: uv sync

    - name: Run system tests
      run: |
        uv run pytest system_tests/tests/ \
          --binary builds/Release/src/rtl_airband \
          --nfm-binary builds/Release_nfm/src/rtl_airband \
          --mode thorough \
          -v
